/* ============================================================
   engine.js  —  the match runner.

   It owns almost no rules any more. It wires three independent
   pieces together and runs the clock:

       physics.js   the World  — floor, furniture, pets, bodies
       leagues.js   the League — which rule-set to build
       a league folder under leagues/ — the rules themselves

   Everything the rest of the app used to read off the engine is still
   here (engine.robots, engine.owner, engine.scores, engine.dock …), so
   the renderer, the map maker and the match page did not have to change.
   Organizers do not edit this file. Coordinates: x,y in metres, origin
   at the corner (0,0), heading in radians, counter-clockwise.
   ============================================================ */

const MATCH_DEFAULTS = {
  matchSeconds: 180,   // match length (seconds) — set by the referee
  redName: 'Team 1',
  blueName: 'Team 2',
  // FINAL mode: the CAT becomes a hazard — every painted tile it walks over
  // turns WHITE again and the team that had painted it loses that point.
  finalMode: false,
  league: null,        // 'fs' | 'u14' | 'u19' | any league added later
  secondary: false,    // kept for older links: same thing as league 'u19'
};

// The robot's code runs 10 times per second, so `timer = 10` lasts exactly 1 second.
const CONTROL_DT = 0.1;

const _clamp = (v, lo, hi) => (v < lo ? lo : (v > hi ? hi : v));

class Engine {
  constructor(cfg = {}) {
    // ---- which league are we playing? ----
    const wanted = cfg.league || (cfg.secondary ? 'u19' : null);
    const def = (Leagues.get(wanted) || Leagues.get('u14') || Leagues.all()[0]);
    if (!def) throw new Error('no league is registered — load a league folder listed in leagues/manifest.js');
    this.league = def;

    // The World owns the house; its cfg is THE cfg (a custom map rewrites W/H/tile
    // inside it), so everything downstream reads one object. A league can ask for
    // a round arena instead of a house.
    // Single-player: only the red robot exists. Head-to-head leagues (the sumo
    // arena) need two bodies by their very nature, so they ignore the setting.
    const solo = (+cfg.players === 1) && !def.arena;

    // a league can bring its own arena (sumo) or its own HOUSE with rooms
    // (assistive); a map the user picked in the setup panel still wins.
    // def.world is the league's PRIVATE re-tune of the shared physics
    // (maxSpeed, maxRange, robotRadius, …): it merges under the caller's cfg,
    // so physics.js defaults stay untouched and no other league feels it.
    const base = Object.assign({}, def.world || {}, cfg);
    const wc = def.arena ? Object.assign({}, base, { arena: def.arena, map: null })
      : (def.map && !cfg.map) ? Object.assign({}, base, { map: def.map })
        : base;
    wc.solo = solo;
    this.world = new RobotWorld.World(wc);
    this.solo = solo;
    this.cfg = this.world.cfg;
    this.arena = this.world.arena;
    this.robotModel = def.robot || 'vacuum';

    // What each team built in the robot builder. Falls back to the league's
    // suggested kit, and then to the classic rig. A saved build with NO parts
    // at all is a robot with no senses — that only ever means the team clicked
    // straight past the builder, so the league's rig drives instead (their
    // chassis shape and paint still count).
    if (typeof RobotParts !== 'undefined') {
      const kits = cfg.kits || {};
      for (const k of this.world.teams) {
        const built = kits[k] ? RobotParts.Loadout.from(kits[k]) : null;
        if (built && built.parts.length) { this.world.robots[k].kit = built; continue; }
        // `kit:` is either the name of a preset in robot-parts.js or the league's
        // OWN parts list, `{ parts: [...] }` — Loadout.from() reads both, so a
        // league can spell out a rig nothing else uses without the shared
        // catalogue having to grow a preset for it.
        const kit = RobotParts.Loadout.from(def.kit || 'classic');
        if (built) { kit.body = built.body; kit.paint = built.paint; }
        this.world.robots[k].kit = kit;
      }
    }
    const match = Object.assign({}, MATCH_DEFAULTS, def.defaults, cfg);
    this.cfg.matchSeconds = match.matchSeconds;
    this.cfg.redName = match.redName;
    this.cfg.blueName = match.blueName;
    this.cfg.finalMode = match.finalMode;
    this.cfg.league = def.id;

    // ---- the rule-set ----
    // cfg.pets, when explicitly true/false, overrides the league's own rule —
    // the setup panel ships the pets OFF by default and a tick lets them in
    const over = { finalMode: this.cfg.finalMode };
    if (this.cfg.dockBox != null) over.dockBox = this.cfg.dockBox;   // a league may ignore it
    if (this.cfg.startPose) over.startPose = this.cfg.startPose;     // sumo: the shikiri gamble
    if (cfg.pets === true || cfg.pets === false) over.pets = cfg.pets;
    this.mode = Leagues.create(def.id, this.world, over);
    this.cfg.secondary = !!(this.mode.rules && this.mode.rules.battery);

    // ---- aliases, so the renderer / editor / UI see one flat object ----
    const w = this.world;
    this.cols = w.cols; this.rows = w.rows;
    this.obstacles = w.obstacles; this.decor = w.decor; this.walls = w.walls;
    this.pillars = w.pillars; this.columns = w.columns;
    this.rugs = w.rugs; this.purples = w.purples; this.puddles = w.puddles;
    this.oranges = w.oranges || []; this.cyans = w.cyans || [];
    this.doors = w.doors || [];
    this.segments = w.segments;
    this.owner = w.owner; this.terrain = w.terrain; this.free = w.free;
    this.terrainColor = w.terrainColor; this.totalTiles = w.totalTiles;
    this.robots = w.robots; this.cat = w.cat; this.dog = w.dog;
    this.props = w.props;                       // people / intruders a league added
    this.scores = this.mode.scores;
    this.dock = this.mode.dock || null;         // charging station (vacuum U19)
    this.zone = this.mode.zone || null;         // scoring ring (sumo)

    this.elapsed = 0;
    this.running = false;
    this.finished = false;
    this.winner = null; // 'red' | 'blue' | 'draw'

    this.redController = null;
    this.blueController = null;

    // overtime: on a draw the match is extended (+10s, then +5s each time)
    this.overtime = (this.mode.overtime || []).slice();
    this.overtimeCount = 0;
    this.onOvertime = null;   // (secondsAdded, roundNumber) -> void
  }

  // the referee callbacks live on the rule-set, but the page sets them here
  get onRelocate() { return this.mode.onRelocate; }
  set onRelocate(fn) { this.mode.onRelocate = fn; }
  get onWet() { return this.mode.onWet; }
  set onWet(fn) { this.mode.onWet = fn; }
  get onDump() { return this.mode.onDump; }
  set onDump(fn) { this.mode.onDump = fn; }
  get onDumpFull() { return this.mode.onDumpFull; }
  set onDumpFull(fn) { this.mode.onDumpFull = fn; }
  get onDiscover() { return this.mode.onDiscover; }
  set onDiscover(fn) { this.mode.onDiscover = fn; }

  /* ---------------- delegating helpers (unchanged API) ---------------- */

  relocate(color, reason, free) { this.mode.relocate(color, reason, free); }
  readSensors(robot, other) { return this.world.readSensors(robot, other); }
  readKit(robot, other) { return this.world.readKit(robot, other); }
  kitOf(color) { return this.world.robots[color].kit; }
  readColors(robot) { return { here: this.world.colorAt(robot.x, robot.y) }; }
  noseColor(robot) { return this.world.noseColor(robot); }
  // What the scoreboard shows. The base shape is always complete, so a league
  // that implements no hud() of its own still gets a working scoreboard.
  hud() {
    const base = {
      scoreLabel: 'points',
      // per team: { num, label, pct, alert, good } — the second line under the score
      metric: { red: { num: '', label: '', pct: 0 }, blue: { num: '', label: '', pct: 0 } },
      center: null,      // one line under the clock
      chip: null,        // a small pill under that
      battery: false, dock: null, charging: null,
    };
    return this.mode.hud ? Object.assign(base, this.mode.hud()) : base;
  }
  _tileOf(x, y) { return this.world.tileOf(x, y); }
  _pointBlocked(x, y) { return this.world.pointBlocked(x, y); }
  _circleFree(x, y, r) { return this.world.circleFree(x, y, r); }
  _integrate(robot, dt) { this.world.integrate(robot, dt, this.mode.speedMul ? this.mode.speedMul(robot) : 1); }
  _updateBattery(robot, dt) { if (this.mode._updateBattery) this.mode._updateBattery(robot, dt); }

  // Everything the robot's code can see. The base half is the same in every
  // league; the rule-set adds its own (battery, dock, whatever comes next).
  _info(robot, other) {
    // Everything a part CAN report. A part the team never bought is simply
    // absent, and the Python bridge turns that into -1.
    const kit = this.world.readKit(robot, other);
    const base = {
      kit,
      color: kit.color != null ? kit.color : -1,
      bumper: kit.bumper != null ? kit.bumper : 0,
      bumperFront: kit.bumperfront != null ? kit.bumperfront : 0,
      bumperBack: kit.bumperback != null ? kit.bumperback : 0,
      heading: kit.heading != null ? kit.heading : -1,
      x: kit.x != null ? kit.x : -1,
      y: kit.y != null ? kit.y : -1,
      time: this.elapsed,
      timeLeft: Math.max(0, this.cfg.matchSeconds - this.elapsed),
      tilesMine: this.scores[robot.color], tilesRival: other ? this.scores[other.color] : 0,
      world: { W: this.cfg.W, H: this.cfg.H, tile: this.cfg.tile },
      league: this.league.id,
    };
    return this.mode.info ? Object.assign(base, this.mode.info(robot, other)) : base;
  }

  _callController(fn, sensors, info) {
    try {
      const out = fn(sensors, info);
      if (!out) return { left: 0, right: 0 };
      return { left: _clamp(+out.left || 0, -1, 1), right: _clamp(+out.right || 0, -1, 1) };
    } catch (e) {
      console.error('controller error:', e);
      return { left: 0, right: 0 };
    }
  }

  /* ---------------- the clock ---------------- */

  step(dt) {
    if (!this.running || this.finished) return;
    this.elapsed += dt;
    const red = this.robots.red, blue = this.robots.blue;

    // The team's code runs at a fixed 10 Hz; between runs the wheels keep their
    // last command. That is what makes `timer = 10` mean exactly one second.
    if (this.ctrlAcc === undefined) this.ctrlAcc = CONTROL_DT;   // run on the very first step
    this.ctrlAcc += dt;
    if (this.ctrlAcc >= CONTROL_DT) {
      this.ctrlAcc -= CONTROL_DT;
      // the bumper reports whether we touched anything since the last run
      for (const rb of [red, blue]) if (rb) {
        rb.bumper = rb.bumpedSince ? 1 : 0;
        rb.bumperFront = rb.bumpedFrontSince ? 1 : 0;
        rb.bumperBack = rb.bumpedBackSince ? 1 : 0;
        rb.bumpedSince = false; rb.bumpedFrontSince = false; rb.bumpedBackSince = false;
      }
      if (this.redController) {
        const o = this._callController(this.redController, this.world.readSensors(red, blue), this._info(red, blue));
        red.left = o.left; red.right = o.right;
      }
      if (blue && this.blueController) {
        const o = this._callController(this.blueController, this.world.readSensors(blue, red), this._info(blue, red));
        blue.left = o.left; blue.right = o.right;
      }
    }

    if (this.mode.preStep) this.mode.preStep(dt);
    this.world.stepBodies(dt, this.mode.speedMul ? (rb) => this.mode.speedMul(rb) : null);
    if (this.mode.postStep) this.mode.postStep(dt);
    this.zone = this.mode.zone || null;         // a league may move its ring

    // some leagues end early (sumo: first to three rounds)
    if (this.mode.finished && this.mode.finished()) { this.overtime = []; this._finish(); return; }
    if (this.elapsed >= this.cfg.matchSeconds) this._finish();
  }

  // LIVE house editing (the Sims button on the match page): `fn` mutates the
  // world's furniture, then every static structure is rebuilt and the engine's
  // flat aliases are re-pointed at the fresh arrays. Tile-scored leagues
  // recount from the floor itself, so the scoreboard never drifts.
  editHouse(fn) {
    if (this.arena) return;
    fn(this.world);
    this.world.refreshStatics();
    const w = this.world;
    this.obstacles = w.obstacles; this.decor = w.decor; this.walls = w.walls;
    this.pillars = w.pillars; this.columns = w.columns; this.segments = w.segments;
    this.owner = w.owner; this.terrain = w.terrain; this.free = w.free;
    this.terrainColor = w.terrainColor; this.totalTiles = w.totalTiles;
    if (this.mode.recount) this.mode.recount();
  }

  // referee ends the match right now (no overtime, result stands as it is)
  endNow() {
    if (this.finished) return;
    this.overtime = [];
    this._forceEnd = true;       // even a must-win cup game bows to the referee
    this._finish();
  }

  _finish() {
    const result = this.mode.result ? this.mode.result() : 'draw';
    // a draw does not end the match while overtime is left — extend and keep playing
    if (result === 'draw' && this.overtime.length) {
      const add = this.overtime.shift();
      this.cfg.matchSeconds += add;
      this.overtimeCount++;
      if (this.onOvertime) this.onOvertime(add, this.overtimeCount);
      return;
    }
    // SUDDEN DEATH: a bracket game MUST produce a winner — once the normal
    // overtime ladder is spent, a drawn cup match keeps extending +5 s at a
    // time until somebody leads. Only the referee's End Game overrides it.
    if (result === 'draw' && this.cfg.mustWin && !this._forceEnd) {
      this.cfg.matchSeconds += 5;
      this.overtimeCount++;
      if (this.onOvertime) this.onOvertime(5, this.overtimeCount);
      return;
    }
    this.running = false; this.finished = true;
    this.winner = result;
  }
}

if (typeof window !== 'undefined') window.Engine = Engine;
