# -*- coding: utf-8 -*-
"""
tools/app.py — the "Smart Home League.exe" launcher (v3, protected).

The game ships INSIDE the exe as a zip (tools/game_blob.py, generated by
tools/protect.py from the minified pack) and is served straight FROM
MEMORY — no game file ever lands on the player's disk, and what the
browser receives is the minified build.

Flow:
  1. serve the in-memory game on 127.0.0.1 (health-checked)
  2. open Edge/Chrome in --app mode with the proxy disabled
  3. window dies young -> keep serving, open the default browser
  4. log everything to %TEMP%\\shl-log.txt

Build:  python tools/protect.py
        python -m PyInstaller --onefile --noconsole
               --name "Smart Home League" tools\\app.py

Test hook:  SHL_SERVER_ONLY=1  -> port in %TEMP%\\shl-port.txt
"""
import base64
import http.server
import io
import mimetypes
import os
import socketserver
import subprocess
import sys
import tempfile
import threading
import time
import urllib.request
import webbrowser
import zipfile

LOG = os.path.join(tempfile.gettempdir(), 'shl-log.txt')
def log(msg):
    try:
        with open(LOG, 'a', encoding='utf-8') as f:
            f.write(time.strftime('[%H:%M:%S] ') + msg + '\n')
    except OSError:
        pass

# ---- the game: from the embedded blob (exe) or the repo (dev) ----
FILES = {}
try:
    import game_blob
    zf = zipfile.ZipFile(io.BytesIO(base64.b64decode(game_blob.DATA)))
    for name in zf.namelist():
        FILES['/' + name] = zf.read(name)
    log_src = 'memory blob (%d files)' % len(FILES)
except Exception as ex:                       # dev fallback: serve the repo
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    log_src = 'disk fallback: ' + ROOT + ' (' + str(ex)[:60] + ')'

MIME = {'.js': 'text/javascript', '.mjs': 'text/javascript',
        '.json': 'application/json', '.py': 'text/plain; charset=utf-8',
        '.woff2': 'font/woff2', '.wasm': 'application/wasm',
        '.html': 'text/html; charset=utf-8'}

# A secret this run of the app invents. The health check asks for it back,
# so a DIFFERENT program listening on the same port can never be mistaken
# for ours and shown to the teams as if it were the league.
ALIVE = base64.urlsafe_b64encode(os.urandom(18)).decode('ascii').rstrip('=')

class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        path = self.path.split('?')[0].split('#')[0]
        if path == '/__shl_alive':
            body = ALIVE.encode('ascii')
            self.send_response(200)
            self.send_header('Content-Type', 'text/plain; charset=utf-8')
            self.send_header('Content-Length', str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        if path.endswith('/'):
            path += 'index.html'
        body = FILES.get(path)
        if body is None and not FILES:        # dev mode: read from disk
            p = os.path.normpath(os.path.join(ROOT, path.lstrip('/')))
            if p.startswith(ROOT) and os.path.isfile(p):
                body = open(p, 'rb').read()
        if body is None:
            self.send_response(404); self.end_headers()
            return
        ext = os.path.splitext(path)[1].lower()
        ctype = MIME.get(ext) or mimetypes.guess_type(path)[0] or 'application/octet-stream'
        self.send_response(200)
        self.send_header('Content-Type', ctype)
        self.send_header('Content-Length', str(len(body)))
        self.send_header('Cache-Control', 'no-cache')
        self.end_headers()
        self.wfile.write(body)
    def log_message(self, *a):
        pass

class Server(socketserver.ThreadingTCPServer):
    # NOT allow_reuse_address: on Windows SO_REUSEADDR lets you bind a port
    # another process is already listening on, and then the two race and the
    # browser can be handed somebody else's page. Better to fail and move on.
    allow_reuse_address = False
    daemon_threads = True

def start_server():
    # Port 0 asks the OS for a free ephemeral port: random, and free by
    # definition, so it can never collide with a site the teacher already runs
    # on 8000. A few named ports are tried first only when SHL_PORT asks.
    wanted = os.environ.get('SHL_PORT', '').strip()
    tries = []
    if wanted.isdigit():
        tries.append(int(wanted))
    tries.append(0)
    srv = None
    for port in tries:
        try:
            srv = Server(('127.0.0.1', port), Handler)
            break
        except OSError:
            continue
    if srv is None:
        raise OSError('no free port on 127.0.0.1')
    port = srv.server_address[1]
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return port

def healthy(base, tries=20):
    """True only when the server on this port is OURS. The token is generated
    fresh each run, so another program answering on the same port cannot pass."""
    probe = base + '/__shl_alive'
    for _ in range(tries):
        try:
            with urllib.request.urlopen(probe, timeout=1) as r:
                if r.status == 200 and r.read().decode('utf-8', 'replace').strip() == ALIVE:
                    return True
        except OSError:
            pass
        time.sleep(0.25)
    return False

def find_browser():
    cands = [
        r'%ProgramFiles(x86)%\Microsoft\Edge\Application\msedge.exe',
        r'%ProgramFiles%\Microsoft\Edge\Application\msedge.exe',
        r'%LocalAppData%\Microsoft\Edge\Application\msedge.exe',
        r'%ProgramFiles%\Google\Chrome\Application\chrome.exe',
        r'%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe',
        r'%LocalAppData%\Google\Chrome\Application\chrome.exe',
        r'%ProgramFiles%\BraveSoftware\Brave-Browser\Application\brave.exe',
    ]
    for c in cands:
        p = os.path.expandvars(c)
        if os.path.isfile(p):
            return p
    return None

def main():
    log('--- Smart Home League starting ---')
    log('game source: ' + log_src)
    port = start_server()
    base = 'http://127.0.0.1:%d' % port
    url = base + '/index.html'
    log('server on port %d (chosen by the system, so nothing else can hold it)' % port)

    if os.environ.get('SHL_SERVER_ONLY'):
        open(os.path.join(tempfile.gettempdir(), 'shl-port.txt'), 'w').write(str(port))
        log('server-only mode')
        threading.Event().wait()

    # Only OUR server may be opened. If the token does not come back, something
    # else is on this port and showing it would hand the teams the wrong page.
    if not healthy(base):
        log('THE SERVER ON THIS PORT IS NOT OURS - refusing to open a browser')
        try:
            import ctypes
            ctypes.windll.user32.MessageBoxW(
                None,
                'Smart Home League could not start its own local server.\n\n'
                'Another program on this computer answered first. Close any other '
                'local server (or restart the computer) and open the app again.\n\n'
                'Details are in: ' + LOG,
                'Smart Home League', 0x10)
        except Exception:
            pass
        return

    log('health check OK')
    exe = find_browser()
    if exe:
        log('browser: ' + exe)
        profile = os.path.join(tempfile.gettempdir(), 'shl-appwindow')
        p = subprocess.Popen([
            exe, '--app=' + url,
            '--user-data-dir=' + profile,
            '--proxy-server=direct://', '--proxy-bypass-list=<-loopback>',
            '--no-first-run', '--no-default-browser-check',
            '--disable-background-networking',
        ])
        t0 = time.time()
        p.wait()
        lived = time.time() - t0
        log('app window closed after %.1f s' % lived)
        if lived > 5:
            return
        log('window died young — falling back to the default browser')
    else:
        log('no Edge/Chrome found — using the default browser')

    webbrowser.open(url)
    log('default browser opened; serving until this process is closed')
    threading.Event().wait()

if __name__ == '__main__':
    main()
