# -*- coding: utf-8 -*-
"""
tools/protect.py — build the PROTECTED hand-out.

Takes SmartHome-TeamPack and produces SmartHome-Protected:
  * every .js file is minified + name-mangled with terser (unreadable,
    comments gone) — cross-file globals are kept so nothing breaks
  * the big inline <script> blocks in the .html files get the same
  * everything else is copied as-is
  * finally the whole pack is zipped into tools/game_blob.py as base64,
    so the exe can serve the game FROM MEMORY — no game files ever land
    on the player's disk

Honesty note: this raises the bar a lot (no readable source, no files),
but nothing that runs on someone's machine is uncopyable in principle.
"""
import base64
import io
import os
import re
import shutil
import subprocess
import sys
import zipfile

DOCS = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(DOCS, 'SmartHome-TeamPack')
DST = os.path.join(DOCS, 'SmartHome-Protected')
TOOLS = os.path.dirname(os.path.abspath(__file__))
TERSER = shutil.which('terser') or shutil.which('terser.cmd')

# keep it working: locals get mangled, cross-file globals stay
TERSER_ARGS = ['--compress', 'passes=2', '--mangle', '--format', 'comments=false']

def minify_js(code):
    r = subprocess.run([TERSER] + TERSER_ARGS, input=code.encode('utf-8'),
                       capture_output=True)
    if r.returncode != 0:
        raise RuntimeError(r.stderr.decode('utf-8', 'replace')[:400])
    return r.stdout.decode('utf-8')

def protect_html(text):
    # minify every inline <script> that has no src=
    out, pos = [], 0
    for m in re.finditer(r'<script((?![^>]*\bsrc=)[^>]*)>(.*?)</script>', text, re.S):
        out.append(text[pos:m.start(2)])
        body = m.group(2)
        attrs = m.group(1)
        # only real JavaScript: the sample-code blocks (type="text/python",
        # text/plain templates, …) must stay exactly as written
        tm = re.search(r'type\s*=\s*["\']([^"\']+)', attrs)
        is_js = not tm or tm.group(1) in ('text/javascript', 'module', 'application/javascript')
        out.append(minify_js(body) if (is_js and body.strip()) else body)
        pos = m.end(2)
    out.append(text[pos:])
    return ''.join(out)

# TeamKit is what make-kits.py builds out of the live repo. TeamPack is the
# same thing without the .md files — the exact set the teams are allowed to
# see. Rebuilding it here means the .exe, the Mac file and the website can
# never again be minified from a stale hand-made copy.
TEAMKIT = os.path.join(TOOLS, '..', 'TeamKit')

def refresh_teampack():
    kit = os.path.abspath(TEAMKIT)
    if not os.path.isdir(kit):
        print('  (no TeamKit — run tools/make-kits.py first; using SmartHome-TeamPack as it stands)')
        return
    if os.path.isdir(SRC):
        shutil.rmtree(SRC)
    shutil.copytree(kit, SRC, ignore=shutil.ignore_patterns('*.md'))
    print('  TeamPack refreshed from TeamKit')

def main():
    if not TERSER:
        sys.exit('terser not found — npm install -g terser')
    refresh_teampack()
    if os.path.isdir(DST):
        shutil.rmtree(DST)
    shutil.copytree(SRC, DST)
    n_js = n_html = 0
    for root, _dirs, files in os.walk(DST):
        for f in files:
            path = os.path.join(root, f)
            if f.endswith('.min.js'):
                continue                     # vendor is already minified
            if f.endswith('.js'):
                code = io.open(path, encoding='utf-8').read()
                io.open(path, 'w', encoding='utf-8').write(minify_js(code))
                n_js += 1
            elif f.endswith('.html'):
                text = io.open(path, encoding='utf-8').read()
                io.open(path, 'w', encoding='utf-8').write(protect_html(text))
                n_html += 1
    print('minified: %d js, %d html' % (n_js, n_html))

    # ---- the in-memory blob for the exe ----
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as z:
        for root, _dirs, files in os.walk(DST):
            for f in files:
                if f.endswith('.command'):
                    continue                 # the mac launcher is not served
                p = os.path.join(root, f)
                z.write(p, os.path.relpath(p, DST).replace('\\', '/'))
    blob = base64.b64encode(buf.getvalue()).decode('ascii')
    with io.open(os.path.join(TOOLS, 'game_blob.py'), 'w', encoding='ascii') as f:
        f.write('# generated by tools/protect.py - the game, zipped + base64\n')
        f.write('DATA = (\n')
        for i in range(0, len(blob), 100):
            f.write("'" + blob[i:i + 100] + "'\n")
        f.write(')\n')
    print('game_blob.py: %.1f MB' % (len(blob) / 1e6))

if __name__ == '__main__':
    main()
